<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>SAML ERROR</title>

        {{ $app->assets($app['app.assets.base'], $app['cockpit/version']) }}
    </head>
    <body>

        <div class="uk-container uk-container-center">

            <h1 class="uk-text-bold uk-margin-large-top"><?=($title ?? 'SAML ERROR')?></h1>

            <div class="uk-panel-box uk-panel-card">
                <?=implode(', ', $errors)?>
            </div>

            @if(isset($attributes) && $app->module('saml')->config('debug', false))
            <div class="uk-panel-framed uk-margin">
                <h3>Attributes</h3>

                @foreach($attributes as $key => $val)
                <div class="uk-margin-small-top uk-text-small">
                    <div class="uk-text-bold">{{$key}}:</div>
                    <div class="uk-margin-small-top">{{json_encode($val)}}</div>
                </div>
                @endforeach
            </div>
            @endif

            <p class="uk-text-small uk-text-muted">Generated by Cockpit SAML addon</p>
        </div>

    </body>
</html>
